import pytest
import os
import json
from datetime import datetime, timezone
from unittest.mock import AsyncMock, patch, MagicMock
from decimal import Decimal
import enum

from core.config import settings
from infrastructure.cache import cache_response
from services.pricing_engine import get_price_snapshot
from repositories.portfolio_repo import portfolio_repo, PortfolioSchema
from models.user_data import UserPortfolio

# ==============================================================================
# AUDIT CONCERN 1: ALEMBIC SCHEMA VERSIONING VALIDATION
# ==============================================================================
def test_alembic_configuration_integrity():
    """Verify that Alembic is initialized, env.py dynamically discovers all metadata columns."""
    from alembic.config import Config
    from alembic import script
    
    # Assert alembic.ini is present at root level of backend
    ini_path = "alembic.ini"
    assert os.path.exists(ini_path), "alembic.ini is missing from backend directory"
    
    # Load Config programmatically
    alembic_cfg = Config(ini_path)
    script_directory = script.ScriptDirectory.from_config(alembic_cfg)
    
    # Assert migrations versions folder is configured and initial migration is recorded
    revisions = list(script_directory.walk_revisions())
    assert len(revisions) >= 1, "Initial schema revision has not been generated by Alembic"
    
    # Assert env.py imports metadata correctly
    env_py_path = os.path.join("alembic", "env.py")
    assert os.path.exists(env_py_path), "alembic/env.py is missing"
    with open(env_py_path, "r") as f:
        env_content = f.read()
        assert "target_metadata = Base.metadata" in env_content, "target_metadata is not configured correctly in env.py"
        assert "from models.user_data import" in env_content, "Models are not imported in env.py"


# ==============================================================================
# AUDIT CONCERN 2: PRICING ENGINE ASYNC HTTPX NON-BLOCKING VERIFICATION
# ==============================================================================
@pytest.mark.asyncio
async def test_pricing_engine_async_httpx_client():
    """Verify that pricing engine executes non-blocking asynchronous requests using HTTPX."""
    symbol = "RELIANCE.NS"
    mock_token = "mock_upstox_token_123"
    
    # Mock dynamic resolve of Upstox keys and active token
    with patch("services.pricing_engine.get_active_upstox_token", return_value=mock_token), \
         patch("services.pricing_engine.resolve_upstox_keys", return_value={symbol: "NSE_EQ|RELIANCE"}), \
         patch("services.pricing_engine.upsert_cached_price", new_callable=AsyncMock):
         
        # High fidelity Upstox response payload
        upstox_payload = {
            "status": "success",
            "data": {
                "NSE_EQ|RELIANCE": {
                    "symbol": "RELIANCE",
                    "last_price": 2450.50,
                    "close": 2400.00,
                    "volume": 1500000,
                    "ohlc": {
                        "close": 2400.00
                    }
                }
            }
        }
        
        # Instantiate httpx Response mock
        mock_response = MagicMock()
        mock_response.status_code = 200
        mock_response.json.return_value = upstox_payload
        
        # Patch httpx.AsyncClient.get to run completely asynchronously
        with patch("httpx.AsyncClient.get", return_value=mock_response) as mock_get:
            snapshot = await get_price_snapshot(symbol, max_age_seconds=0)
            
            # Assert HTTPX AsyncClient was called instead of blocking requests library
            mock_get.assert_called_once()
            call_url = mock_get.call_args[0][0]
            assert "api.upstox.com" in call_url
            
            # Assert response snapshot was constructed correctly
            assert snapshot is not None
            assert snapshot.symbol == symbol
            assert snapshot.last_price == 2450.50
            assert snapshot.previous_close == 2400.00
            assert snapshot.change_amount == 50.50
            assert snapshot.currency == "INR"
            assert snapshot.source == "upstox_quotes_api"


# ==============================================================================
# AUDIT CONCERN 3: ROBUST CACHE SERIALIZATION (FASTAPI JSONABLE ENCODER)
# ==============================================================================
class MockCustomEnum(enum.Enum):
    ALPHA = "alpha"
    BETA = "beta"

@pytest.mark.asyncio
async def test_cache_serialization_robustness():
    """Verify that cache_response decorator serializes datetime, custom enum, and decimal types successfully."""
    # Build mock data structure containing complex types that normally fail standard json.dumps
    complex_data = {
        "timestamp": datetime.now(timezone.utc),
        "ratio": Decimal("3.14159"),
        "status": MockCustomEnum.ALPHA,
        "raw_model": {"portfolio_id": 999, "is_active": True}
    }
    
    execution_counter = 0
    
    @cache_response(ttl=30, prefix="test:hardcore")
    async def sample_cached_service():
        nonlocal execution_counter
        execution_counter += 1
        return complex_data
        
    mock_redis = AsyncMock()
    mock_redis.get.return_value = None # Cache miss first
    
    with patch("infrastructure.cache.redis_client", mock_redis):
        # Execute the service
        result = await sample_cached_service()
        
        # Assert database was hit once
        assert execution_counter == 1
        assert result == complex_data
        
        # Verify redis_client.set was invoked with a successfully serialized JSON string
        mock_redis.set.assert_called_once()
        cache_key, serialized_payload, ttl = mock_redis.set.call_args[0]
        
        assert "test:hardcore:sample_cached_service" in cache_key
        # Verify that complex types got serialized successfully (no TypeError)
        decoded = json.loads(serialized_payload)
        assert decoded["status"] == "alpha"
        assert float(decoded["ratio"]) == 3.14159
        assert "timestamp" in decoded


# ==============================================================================
# AUDIT CONCERN 4: SECURITY HYGIENE ENVIRONMENT FALLBACK KEYS
# ==============================================================================
def test_security_fallback_api_key_configuration():
    """Verify that FALLBACK_API_KEY is defined in Pydantic Settings, loaded from .env, and not hardcoded."""
    # Verify environment settings attributes
    assert hasattr(settings, "FALLBACK_API_KEY"), "FALLBACK_API_KEY property is missing from config settings class"
    
    # Assert that no fake values are hardcoded in config.py
    # Re-reading config file dynamically to ensure "fake_finnhub_key" is absent
    config_file_path = os.path.join("core", "config.py")
    with open(config_file_path, "r") as f:
        config_content = f.read()
        assert "fake_finnhub_key" not in config_content, "Mock fallback API credentials are leak-vulnerable (hardcoded in config.py)"


# ==============================================================================
# AUDIT CONCERN 5: BASE REPOSITORY PURE ASYNC CRUD VALIDATION
# ==============================================================================
@pytest.mark.asyncio
async def test_base_repository_pure_async_crud():
    """Verify BaseRepository operates CRUD queries natively using AsyncSessionLocal rather than synchronous thread executors."""
    # Seed mock portfolio data
    portfolio_id = "port-777"
    user_id = 999
    portfolio_name = "Core Infrastructure Portfolio"
    
    portfolio_record = PortfolioSchema(
        id=portfolio_id,
        user_id=str(user_id),
        name=portfolio_name,
        total_value=250000.0,
        currency="USD"
    )
    
    # Mocking Database AsyncSession context and calls
    mock_db_session = AsyncMock()
    mock_db_session.__aenter__.return_value = mock_db_session
    mock_db_session.add = MagicMock()
    
    # Setup mock portfolio instance
    db_obj = UserPortfolio(id=portfolio_id, user_id=user_id, name=portfolio_name)
    mock_db_session.refresh.return_value = None
    
    # Setup database scalar/execute results
    mock_res_select = MagicMock()
    mock_res_select.scalar_one_or_none.return_value = db_obj
    
    mock_res_select_all = MagicMock()
    mock_res_select_all.scalars.return_value.all.return_value = [db_obj]
    
    mock_db_session.execute.side_effect = [mock_res_select, mock_res_select_all, mock_res_select]
    
    # Patch AsyncSessionLocal constructor to return our mock session
    with patch("database.connection.AsyncSessionLocal", return_value=mock_db_session):
        # 1. Test creation
        created = await portfolio_repo.create(portfolio_record)
        assert created is not None
        assert created.name == portfolio_name
        assert mock_db_session.add.called
        assert mock_db_session.commit.called
        
        # 2. Test async select (get_by_id)
        fetched = await portfolio_repo.get_by_id(portfolio_id)
        assert fetched is not None
        assert fetched.id == portfolio_id
        assert fetched.name == portfolio_name
        
        # 3. Test async select all (get_by_user_id)
        all_portfolios = await portfolio_repo.get_by_user_id(str(user_id))
        assert len(all_portfolios) == 1
        assert all_portfolios[0].name == portfolio_name
        
        # 4. Test async update
        update_data = {"name": "Refactored Core Portfolio"}
        # setup next execute return
        db_obj.name = "Refactored Core Portfolio"
        mock_db_session.execute.side_effect = [mock_res_select]
        
        updated = await portfolio_repo.update(portfolio_id, update_data)
        assert updated.name == "Refactored Core Portfolio"
        assert mock_db_session.commit.called
        
        # 5. Test async delete
        mock_db_session.execute.side_effect = [mock_res_select]
        deleted = await portfolio_repo.delete(portfolio_id)
        assert deleted is True
        assert mock_db_session.delete.called
