"use client";

import { useState } from "react";
import { Terminal, Code, Cpu, Globe, Key, Copy, Check } from "lucide-react";
import { motion } from "framer-motion";

export default function ApiPage() {
  const [activeEndpoint, setActiveEndpoint] = useState("get-signals");
  const [copied, setCopied] = useState(false);

  const endpoints = [
    {
      id: "get-signals",
      method: "GET",
      path: "/v1/models/signals",
      desc: "Retrieve real-time directional quant signals generated by the LSTM and XGBoost neural model cores.",
      params: [
        { name: "symbol", type: "string", req: true, desc: "Stock or asset ticker (e.g., TSLA, NVDA)" },
        { name: "conviction", type: "float", req: false, desc: "Filter results by minimum conviction score (0.0 to 1.0)" }
      ],
      response: `{
  "status": "success",
  "data": {
    "symbol": "TSLA",
    "timestamp": "2026-05-26T11:42:00Z",
    "signal": "BULLISH",
    "conviction_score": 0.87,
    "fair_value_projection": 240.00,
    "risk_index": "MEDIUM",
    "action_recommended": "ACCUMULATE"
  }
}`,
      curl: `curl -X GET "https://api.rautrex.com/v1/models/signals?symbol=TSLA" \\
  -H "Authorization: Bearer YOUR_API_KEY"`
    },
    {
      id: "get-market",
      method: "GET",
      path: "/v1/market/prices",
      desc: "Fetch real-time direct price metrics mapping structural indicators and volatilities.",
      params: [
        { name: "tickers", type: "string", req: true, desc: "Comma-separated list of asset tickers (e.g. AAPL,BTC)" }
      ],
      response: `{
  "status": "success",
  "data": [
    {
      "ticker": "AAPL",
      "price": 210.00,
      "change_percent": 1.25,
      "volume_24h": 58392010,
      "volatility_index": "LOW"
    }
  ]
}`,
      curl: `curl -X GET "https://api.rautrex.com/v1/market/prices?tickers=AAPL" \\
  -H "Authorization: Bearer YOUR_API_KEY"`
    }
  ];

  const handleCopy = (text: string) => {
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const endpoint = endpoints.find(e => e.id === activeEndpoint)!;

  return (
    <div className="bg-[var(--bg-primary)] min-h-screen text-[var(--text-primary)] font-sans">
      {/* Hero Header */}
      <section className="bg-[#2C2A1E] text-[#F5F0E8] py-28 px-6 border-b border-border/20">
        <div className="max-w-4xl mx-auto space-y-6">
          <p className="text-accent text-xs font-black uppercase tracking-[0.3em]">Developer Portal</p>
          <h1 className="text-4xl md:text-6xl font-extrabold tracking-tight text-[#F5F0E8]">Developer API Docs</h1>
          <p className="text-[#EDE8DC]/80 text-base md:text-lg max-w-xl leading-relaxed">
            Integrate institutional-grade quantitative calculations, live directional forecasts, and portfolio analytics directly into your custom software stacks.
          </p>
        </div>
      </section>

      {/* Main Grid */}
      <section className="py-24 px-6 max-w-7xl mx-auto grid grid-cols-1 lg:grid-cols-12 gap-12">
        {/* Left endpoint list */}
        <div className="lg:col-span-4 space-y-6">
          <div className="space-y-2">
            <h2 className="text-accent text-xs font-black uppercase tracking-[0.3em]">API Desks</h2>
            <h2 className="text-2xl font-bold tracking-tight text-foreground">Endpoints</h2>
          </div>

          <div className="flex flex-col gap-2">
            {endpoints.map(ep => (
              <button 
                suppressHydrationWarning
                key={ep.id}
                onClick={() => {
                  setActiveEndpoint(ep.id);
                  setCopied(false);
                }}
                className={`w-full p-4 rounded-xl border text-left flex gap-3 items-center transition-all ${
                  activeEndpoint === ep.id 
                    ? "border-accent bg-surface shadow-sm font-bold" 
                    : "border-border/60 bg-surface/50 hover:border-accent/40"
                }`}
              >
                <span className={`text-[10px] font-bold px-2 py-0.5 rounded tracking-wider ${
                  ep.method === "GET" ? "bg-positive/10 text-positive" : "bg-accent/10 text-accent"
                }`}>
                  {ep.method}
                </span>
                <span className="font-mono text-xs text-foreground">{ep.path}</span>
              </button>
            ))}
          </div>
        </div>

        {/* Right detailed documentation panel */}
        <div className="lg:col-span-8">
          <div className="glass-panel p-8 md:p-10 rounded-[28px] bg-surface border border-border shadow-md space-y-6">
            <div>
              <div className="flex items-center gap-3 mb-2">
                <span className="text-[10px] font-bold bg-positive/10 text-positive px-2 py-0.5 rounded tracking-widest uppercase">
                  {endpoint.method}
                </span>
                <span className="font-mono text-base font-black text-foreground">{endpoint.path}</span>
              </div>
              <p className="text-text-secondary text-xs leading-relaxed font-medium">{endpoint.desc}</p>
            </div>

            {/* Parameters Table */}
            <div className="space-y-3">
              <h4 className="text-xs font-bold text-foreground uppercase tracking-wider">Query Parameters</h4>
              <div className="border border-border/60 rounded-xl overflow-hidden shadow-sm">
                <table className="w-full text-left border-collapse text-xs">
                  <thead>
                    <tr className="bg-[var(--bg-secondary)]/50 border-b border-border/60">
                      <th className="p-3 font-bold text-foreground">Parameter</th>
                      <th className="p-3 font-bold text-foreground">Type</th>
                      <th className="p-3 font-bold text-foreground">Required</th>
                      <th className="p-3 font-bold text-text-muted">Description</th>
                    </tr>
                  </thead>
                  <tbody>
                    {endpoint.params.map((p, i) => (
                      <tr key={i} className="border-b border-border/40 last:border-b-0">
                        <td className="p-3 font-mono font-bold text-foreground">{p.name}</td>
                        <td className="p-3 font-mono text-accent">{p.type}</td>
                        <td className="p-3 font-bold">{p.req ? "Yes" : "No"}</td>
                        <td className="p-3 text-text-secondary">{p.desc}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>

            {/* Code request/response blocks */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6 pt-4 border-t border-border/40">
              {/* Shell curl request */}
              <div className="space-y-2">
                <div className="flex justify-between items-center">
                  <h4 className="text-xs font-bold text-foreground uppercase tracking-wider">HTTP Request</h4>
                  <button 
                    suppressHydrationWarning
                    onClick={() => handleCopy(endpoint.curl)}
                    className="text-[10px] text-accent hover:text-accent/80 font-bold uppercase tracking-wider flex items-center gap-1"
                  >
                    {copied ? <Check size={10} /> : <Copy size={10} />}
                    {copied ? "Copied" : "Copy"}
                  </button>
                </div>
                <pre className="p-4 bg-[#2C2A1E] border border-border/10 rounded-xl text-[10px] font-mono text-[#EDE8DC] overflow-x-auto select-all leading-relaxed max-h-[220px]">
                  {endpoint.curl}
                </pre>
              </div>

              {/* Response output */}
              <div className="space-y-2">
                <h4 className="text-xs font-bold text-foreground uppercase tracking-wider">JSON Response</h4>
                <pre className="p-4 bg-[#2C2A1E] border border-border/10 rounded-xl text-[10px] font-mono text-[#EDE8DC] overflow-x-auto leading-relaxed max-h-[220px]">
                  {endpoint.response}
                </pre>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}
