"use client";

import { AlertOctagon, TrendingDown, RefreshCw, BarChart2 } from "lucide-react";
import { motion } from "framer-motion";

export default function DisclaimerPage() {
  return (
    <div className="bg-[var(--bg-primary)] min-h-screen text-[var(--text-primary)] font-sans">
      {/* Header Banner */}
      <section className="bg-[#2C2A1E] text-[#F5F0E8] py-20 px-6 text-center border-b border-border/20">
        <div className="max-w-4xl mx-auto space-y-4">
          <p className="text-accent text-xs font-black uppercase tracking-[0.3em]">Compliance & Safety</p>
          <h1 className="text-4xl md:text-5xl font-extrabold tracking-tight text-[#F5F0E8]">Risk Disclaimer</h1>
          <p className="text-[#EDE8DC]/80 text-xs md:text-sm max-w-lg mx-auto leading-relaxed">
            Please read this financial risk warning carefully before utilizing any tools, models, or indicators on the RAUTREX terminal.
          </p>
        </div>
      </section>

      {/* Content */}
      <section className="py-20 px-6 max-w-4xl mx-auto">
        <div className="glass-panel p-8 md:p-12 rounded-[28px] bg-surface border border-border shadow-md space-y-8 text-xs md:text-sm text-text-secondary leading-relaxed">
          
          <div className="p-6 bg-negative/5 border border-negative/20 rounded-2xl flex gap-4 items-start">
            <AlertOctagon size={24} className="text-negative shrink-0" />
            <div className="space-y-2">
              <h3 className="text-sm font-bold text-negative uppercase tracking-wide">High Risk Investment Warning</h3>
              <p className="text-[11px] leading-relaxed text-text-secondary">
                Trading securities, options, currencies, and digital assets carries a high level of risk and may not be suitable for all investors. Leveraged trading or structural options deployment can result in rapid capital depletion exceeding your initial investments.
              </p>
            </div>
          </div>

          <div className="space-y-4">
            <h3 className="text-lg font-bold text-foreground flex items-center gap-2">
              <BarChart2 size={18} className="text-accent" /> 1. No Professional Financial Advice
            </h3>
            <p>
              RAUTREX is not registered as a broker-dealer or a financial advisor with the SEC, FINRA, or any global financial regulatory body. All content, signals, projections, and reports are provided **strictly for educational and analytical research purposes**. 
            </p>
            <p>
              None of the outputs generated by our Monte Carlo engine or LSTM models constitute direct recommendations to purchase, sell, or hold any security.
            </p>
          </div>

          <div className="space-y-4">
            <h3 className="text-lg font-bold text-foreground flex items-center gap-2">
              <RefreshCw size={18} className="text-accent" /> 2. Backtest Limitations & Regressions
            </h3>
            <p>
              Backtesting represents simulated historical performance evaluated against static datasets. **Past performance is not indicative or a guarantee of future returns**. 
            </p>
            <p>
              Simulated indicators are subjected to specific limitations (such as bid-ask spread variances, borrowing costs, transaction latencies, and market liquidity shifts) which can cause real trading results to differ significantly from backtested returns.
            </p>
          </div>

          <div className="space-y-4">
            <h3 className="text-lg font-bold text-foreground flex items-center gap-2">
              <TrendingDown size={18} className="text-accent" /> 3. Stochastic & Model Limits
            </h3>
            <p>
              Stochastic processes—including Geometric Brownian Motion used in our Monte Carlo simulations—operate on idealized assumptions (such as normal distributions of log-returns) that do not always capture extreme market events, liquidity crises, or "black swan" systemic failures. Models can and do fail during high-volatility events.
            </p>
          </div>

          <div className="pt-6 border-t border-border/40 text-[10px] text-text-muted text-center font-mono">
            RAUTREX LEGAL & PRIVACY OPERATIONS • NEW DELHI, INDIA
          </div>
        </div>
      </section>
    </div>
  );
}
